### PR TITLE
Add CSS variables for background colors

### LINKED ISSUE #124: Use a theme CSS variable instead of a Material Design color for the highlight animation
Hi! 👋 

## Context

I am creating a JupyterLab theme and as `jupyterlab-execute-time` is one of the extensions used, I would like to be able to guarantee the customization of its styles completely using the CSS variables defined in JupyterLab themes.

## Problem

Currently, one of the colors used in the highlight animation is one of the Material Design colors and not one of the semantic colors defined in JupyterLab themes, for example: https://github.com/deshaw/jupyterlab-execute-time/blob/985728d1b9889f52a8c0f3a646739849c0f9bbac/style/base.css#L1-L9

## Possible solution

The Material Design color used, `--md-blue-100`, corresponds to `--jp-brand-color3` in the default JupyterLab themes:

- https://github.com/jupyterlab/jupyterlab/blob/v4.3.0a1/packages/theme-light-extension/style/variables.css#L222
- https://github.com/jupyterlab/jupyterlab/blob/v4.3.0a1/packages/theme-dark-extension/style/variables.css#L225
- https://github.com/jupyterlab/jupyterlab/blob/v4.3.0a1/packages/theme-dark-high-contrast-extension/style/variables.css#L225

So, a possible solution would be to change `var(--md-blue-100, #9fccff)` to `var(--jp-brand-color3, #bbdefb)`, using the [current Material Design color](https://github.com/jupyterlab/jupyterlab/blob/v4.3.0a1/packages/apputils/style/materialcolors.css#L82C18-L82C25) as a fallback.

Let me know your thoughts, please, and if I can open a PR. Thanks! 😄

### PR DESCRIPTION
**Pull request by joaopalmeiro**
Closes #124 

---

Hi! 👋 

As per the discussion on #124, here is a proposal to include two CSS variables to style the (animated) background colors for this extension. The highlight color fallback has also been updated. Let me know what you think, please!

https://github.com/user-attachments/assets/8533b638-32ae-41b0-9cd0-126d20c417c6

Screenshot 2024-07-15 at 18 23 58

### CODE REVIEW

**Comment by joaopalmeiro** [comment]
Hi! 👋 

Sorry to bother you, @krassowski, but any chance you could review this MR, please?

Thanks!

**Review by krassowski — APPROVED** [review]
Looks good to me, as per discussion in https://github.com/deshaw/jupyterlab-execute-time/issues/124

**Comment by joaopalmeiro** [comment]
Thanks, @krassowski!

**Comment by joaopalmeiro** [comment]
Thanks for the reminder! I signed at the time I opened MR. Is there any way to confirm?

**Comment by mlucool** [comment]
Confirmed @joaopalmeiro signed. Merging

**Pull request merged**
