### PR TITLE
Fixes 'Using .* with relational operator'

### PR DESCRIPTION
**Pull request by LunarLanding**
Fixes https://github.com/conda-forge/jupyterlab_execute_time-feedstock/issues/2

### CODE REVIEW

**Comment by mlucool** [comment]
Thanks! Does this mean we need publish a new version?

**Comment by LunarLanding** [comment]
Hi, I just had time to test it now. The issue is still present since the conda-feedstock has not updated. It might be possible to update the build number instead of the version.

**Comment by mlucool** [comment]
Seems like the issue was upstream of this actually: https://github.com/conda-forge/jupyterlab_execute_time-feedstock/pull/3. Try one more time?

**Comment by LunarLanding** [comment]
It works now! Thanks!

**Pull request merged**
